# User config
author: "Provecho"
tagline: "Provecho contenidos"
description: "<p>En 'Los mandamientos gánicos' (1960) Federico Manuel Peralta Ramos clama:</p>
<blockquote><strong>1. Ser gánico.<strong> (Ser gánico significa hacer siempre lo que uno tiene ganas).
</blockquote>
<p>Provecho se trata un poco de eso, un espacio en el que puedo mostrar lo que me dan ganas,
donde se pueden llevar buenas datas y también, incentivarles a que coman rico y vegano por supuesto.</p>"
keywords: "foto producto, comida, vegan, fotografí:wa, crudivegano, cultura sustentable"
email: "fotoprovecho@gmail.com"
linkedin: "https://www.linkedin.com/in/yamila-miglioranza-02a06a210/"
behance: "https://www.behance.net/yammiglioranza"
instagram: "https://www.instagram.com/fotoprovecho/"
github: "https://github.com/provecho/"

# Site config
#baseurl: "/pineapple"
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed


