# User config
author: "Provecho"
tagline: "Provecho contenidos"
description: "<p>En 'Los mandamientos gánicos' (1960) Federico Manuel Peralta Ramos clama:</p>
<blockquote><strong>1. Ser gánico.<strong> (Ser gánico significa hacer siempre<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
lo que uno tiene ganas).
</blockquote>
<p>Provecho se trata un poco de eso, esta no es una pagina especifica de algo, es gran parte de 
todo lo que como individua me interesa:</p>
<ul>
<li>Cultura antiespecista</li>
<li>Fotografía</li>
<li>Reseñas gastronómicas</li>
<li>Arte</li> 
</ul>
<p>Un espacio divertido en el que puedo mostrar lo que hago y donde se pueden llevar buenas datas.
Y también incentivarles a que coman más rico y vegano por supuesto.</p>"
keywords: "foto producto, comida, vegan, fotografia, crudivegano, cultura sustentable"
email: "fotoprovecho@gmail.com"
linkedin: "https://www.linkedin.com/in/yamila-miglioranza-02a06a210/"
behance: "https://www.behance.net/yammiglioranza"
instagram: "https://www.instagram.com/fotoprovecho/"
github: "https://github.com/provecho/"

# Site config
#baseurl: "/pineapple"
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed


